### ISSUE TITLE
Typo on line 27 of envoy-gloo/ci/run_envoy_docker.sh

### ISSUE THREAD

**Issue by jainrahulh** [solo-io/envoy-gloo#112]
envoy-gloo/ci/run_envoy_docker.sh file has a line of code which should be commented perhaps? Running the `make build-arm` or whenever this shell script is invoked give an error.

`./ci/run_envoy_docker.sh: line 27: Since: command not found`

**Comment by DerrickMartinez** [comment]
Yeah this has been there for a while. Thanks for bringing it to their attention again. 

Also having a hell of a time building it for arm64. 1.17 was OK. Would be nice if they are not going to publish docker files to post the compiled envoys here in releases

**Comment by saiskee** [comment]
@jainrahulh @DerrickMartinez Thanks for bringing this to our attention. Fixed by @nfuden  in #143
