### ISSUE TITLE
Envoy with Modsecurity

### ISSUE THREAD

**Issue by StarryVae** [solo-io/envoy-gloo#145]
I tried to compile Envoy with libmodsecurity, but it requires some dynamic libs like xml2, pcre and so on, as a result, to compile or run Envoy, these dynamic libs must be installed in the environment. Is it also nesscessary in Gloo Envoy? PLease help, thanks!

**Comment by yuval-k** [comment]
Unfortunately we are not able to provide further assistance with this matter.
